accountant/urls.py
from django.urls import path

from accountant import views
app_name = 'Accountant'
urlpatterns = [
    path('landing_page', views.landing, name='landing_page'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_in', views.sign_in, name='sign_in'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('stocks', views.stocks, name='stocks'),
    path('products/<int:stock_id>', views.products, name='products'),
    path('new/product/<int:stock_id>', views.new_product, name='new_product'),
    path('new/stock', views.new_stock, name='new_stock'),
    path('customers', views.customers, name='customers'),
    path('customer/sales/<int:customer_id>', views.sales, name='sales'),
    path('add/customer', views.add_customer, name='add_customer'),
    path('add/customer/sale/<int:customer_id>', views.add_sale, name='add_sale')
]

efinance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accountant/', include('accountant.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountant/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Accountant(get_user_model()):
    location = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Accountant'


class Admin_User(get_user_model()):
    location = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Admin'


class Stock(models.Model):
    name = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Stock'


class Product(models.Model):
    name = models.CharField(max_length=250)
    number_of_units = models.IntegerField()
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    buying_price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Product'


class Customer(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    phone_number = models.IntegerField()


class Sale(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    units_sold = models.IntegerField()
    price_per_unit = models.IntegerField()
    total = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Sale'

accountant/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from accountant.models import Accountant, Product, Sale, Stock, Customer


class SignUpForm(UserCreationForm):

    class Meta:
        model = Accountant
        fields = ('username', 'first_name', 'last_name', 'email', 'location')


class AddStockForm(ModelForm):

    class Meta:
        model = Stock
        fields = ('name',)


class AddCustomerForm(ModelForm):

    class Meta:
        model = Customer
        fields = ('first_name', 'last_name', 'phone_number')


class AddProductForm(ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'stock', 'buying_price')


class AddSaleForm(ModelForm):

    class Meta:
        model = Sale
        fields = ('user', 'customer', 'product', 'price_per_unit', 'units_sold', 'total')

accountant/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

# Create your views here.
from accountant.forms import SignUpForm, AddProductForm, AddStockForm, AddCustomerForm, AddSaleForm
from accountant.models import Accountant, Admin_User, Stock, Product, Customer, Sale

app_name = 'Accountant'


def landing(request):
    return render(request, 'accountant/landing_page.html')


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        print(form)
        # pdb.set_trace()
        if form.is_valid():
            farmer = form.save(commit=False)
            farmer.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('Farmer:my_sales')
        else:
            messages.error(request, 'Form Invalid')
            return redirect('Accounts:signup')
    else:
        form = SignUpForm()
    return render(request, 'registration/sign_up.html',{'form':form})


def sign_in(request):
    msg = []

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                if Accountant.objects.filter(user_ptr_id=user.id).exists():
                    return redirect('Accountant:dashboard')
                elif Admin_User.objects.filter(user_ptr_id=user.id).exists():
                    return redirect('Accountant:dashboard')
            else:
                msg.append('You account has been deactivated!')
    else:
        msg.append('Invalid login')
    return render(request, 'registration/sign_in.html', {'errors':msg})


def stocks(request):
    stocks = Stock.objects.all()
    return render(request, 'accountant/view_stocks.html', {'stocks':stocks})


def new_stock(request):
    if request.method == 'POST':
        form = AddStockForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Stock Added Successfully')
            return redirect('Accountant:stocks')
        else:
            messages.error(request, 'Invalid Details Please Try Again')
    return render(request, 'accountant/add_stock.html')


def products(request, stock_id):
    stock = Stock.objects.get(id=stock_id)
    products = Product.objects.filter(stock=stock)
    return render(request, 'accountant/view_products.html', {'products':products, 'stock':stock})


def new_product(request, stock_id):
    stock = Stock.objects.get(id=stock_id)
    form = AddProductForm(request.POST)

    if request.method == 'POST':
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request,'Product Added Successfully')
            return redirect('Accountant:products', stock.id)
        else:
            messages.error(request, 'Failed to add the product')
            return redirect('Accountant:new_product', stock.id)
    else:
        form = AddProductForm()
        return render(request, 'accountant/add_product.html',{'stock':stock, 'form':form})


def dashboard(request):
    return render(request, 'layouts/base.html')


def customers(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers
    }
    return render(request, 'accountant/customers.html', context)


def add_customer(request):
    if request.method == 'POST':
        form = AddCustomerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Customer Added Successfully')
            return redirect('Accountant:customers')
        else:
            messages.error(request, 'Form Validation Failed')
            return redirect('Accountant:customers')
    return render(request, 'accountant/add_customer.html')


def sales(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    customer_sales = Sale.objects.filter(customer=customer)
    context = {
        'customer': customer,
        'customer_sales': customer_sales
    }
    return render(request, 'accountant/sales.html', context)


def add_sale(request, customer_id):
    admin = Admin_User.objects.get(user_ptr_id = request.user.id)
    customer = Customer.objects.get(id=customer_id)
    products = Product.objects.all()
    if request.method == 'POST':
        form = AddSaleForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sale added successfully')
            return redirect('Accountant:sales', customer_id)
        else:
            messages.error(request, 'Form Validation Failed')
            return redirect('Accountant:sales', customer_id)

    context = {
        'admin': admin,
        'customer': customer,
        'products': products
    }
    return render(request, 'accountant/add_sale.html', context)

accountant/templates/accountant/add_customer.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
    <div class="card">
        <div class="card-header">
            <strong>New Product</strong>
        </div>
        <div class="card-body">
    <div class="row">
            <div class="col-md-8">
              <div class="demo-form-wrapper">
                <form class="form form-horizontal"  method="post" action="{% url 'Accountant:add_customer' %}">
                    {% csrf_token %}

                  <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">First Name</label>
                    <div class="col-sm-9">
                      <input id="name" name="first_name" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Last Name</label>
                    <div class="col-sm-9">
                      <input id="name" name="last_name" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Phone Number</label>
                    <div class="col-sm-9">
                      <input id="name" name="phone_number" class="form-control" type="text">
                    </div>
                  </div>
                    <button class="btn btn-success pull-right" type="submit">Create</button>
                </form>
              </div>
            </div>
    </div>
        </div>
    </div>
</div>
{% endblock %}

accountant/templates/accountant/add_product.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content%}
    <div class="col-xs-12">
    <div class="card">
        <div class="card-header">
            <strong>Add New Product</strong>
        </div>
        <div class="card-body">
    <div class="row">
            <div class="col-md-8">
              <div class="demo-form-wrapper">
                <form class="form form-horizontal"  method="post" action="{% url 'Accountant:new_product' stock.id %}">
                    {% csrf_token %}
                  <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Product Name</label>
                    <div class="col-sm-9">
                      <input id="name" name="name" class="form-control" type="text">
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-2">Stock</label>
                    <div class="col-sm-9">
                      <input id="stock" name="stock" class="form-control" type="text" value="{{ stock.id }}">
                    </div>
                  </div>

                  <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-3">Buying Price</label>
                    <div class="col-sm-9">
                      <input id="form-control-3" class="form-control" type="text" name="buying_price" placeholder="">
                    </div>
                  </div>
                    <button type="submit" class="btn btn-success pull-right">Add Product</button>
                </form>
              </div>
            </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

accountant/templates/accountant/add_sale.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
    <div class="card">
        <div class="card-header">
            <strong>Add Sale</strong>
        </div>
        <div class="card-body">
    <div class="row">
            <div class="col-md-8">
              <div class="demo-form-wrapper">
                <form class="form form-horizontal"  method="post" action="{% url 'Accountant:add_sale' customer.id %}">
                    {% csrf_token %}

                  <div class="form-group" hidden>
                    <label class="col-sm-3 control-label" for="form-control-1">User</label>
                    <div class="col-sm-9">
                      <input id="name" name="user" value="{{ admin.id }}" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group" hidden>
                    <label class="col-sm-3 control-label" for="form-control-1">Customer</label>
                    <div class="col-sm-9">
                      <input id="name" name="customer" value="{{ customer.id }}" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="form-control-1">Product</label>
                        <div class="col-sm-9">
                    <select class="custom-select" name="product">
                        <option value="" selected="">--Select a Product--</option>
                        {% for product in products %}
                        <option value="{{ product.id }}">{{ product.name }}</option>
                        {% endfor %}
                      </select>
                        </div>
                    </div>

                    <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Units Sold</label>
                    <div class="col-sm-9">
                      <input id="name" name="units_sold" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Price Per Unit</label>
                    <div class="col-sm-9">
                      <input id="name" name="price_per_unit" class="form-control" type="text">
                    </div>
                  </div>

                    <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Total</label>
                    <div class="col-sm-9">
                      <input id="name" name="total" class="form-control" type="text">
                    </div>
                  </div>
                    <button class="btn btn-success pull-right" type="submit">Create</button>
                </form>
              </div>
            </div>
    </div>
        </div>
    </div>
</div>
{% endblock %}

accountant/templates/accountant/add_stock.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
    <div class="card">
        <div class="card-header">
            <strong>Add New Product</strong>
        </div>
        <div class="card-body">
    <div class="row">
            <div class="col-md-8">
              <div class="demo-form-wrapper">
                <form class="form form-horizontal"  method="post" action="{% url 'Accountant:new_stock' %}">
                    {% csrf_token %}

                  <div class="form-group">
                    <label class="col-sm-3 control-label" for="form-control-1">Stock Title</label>
                    <div class="col-sm-9">
                      <input id="name" name="name" class="form-control" type="text">
                    </div>
                  </div>
                    <button class="btn btn-success pull-right" type="submit">Create</button>
                </form>
              </div>
            </div>
    </div>
        </div>
    </div>
</div>
{% endblock %}

accountant/templates/accountant/customers.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
<div class="card">
    <div class="card-header">
        <strong>Stocks</strong>
        <a class="btn btn-success pull-right" href="{% url 'Accountant:add_customer' %}">New Customer</a>
    </div>
    <div class="card-body">
        <div class="table-flip-scroll table-responsive">
            <table class="table table-striped dataTable">
                <thead>
                <tr>
                    <th>Customer Name</th>
                    <th>Phone Number</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in customers %}
                <tr>
                    <td><a href="{% url 'Accountant:sales' customer.id %}">{{ customer.first_name }} {{ customer.last_name }}</a></td>
                    <td>{{ customer.phone_number}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
</div>
{% endblock %}

accountant/templates/accountant/landing_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Landing page &middot; Elephant Template &middot; The fastest way to build Modern Admin APPS for any platform, browser, or device.</title>
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="{% static 'css/vendor.min.css' %}s">
    <link rel="stylesheet" href="{% static 'css/elephant.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/landing-page.min.css' %}">
  </head>
  <body class="spinner spinner-primary spinner-lg">
    <div class="navbar navbar-default bg-success">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">
            <img class="navbar-brand-logo" src="img/logo-inverse.svg" alt="Elephant">
          </a>
        </div>
        <nav id="navbar" class="navbar-collapse collapse bg-success">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Home</a></li>
            <li><a href="#">Features</a></li>
            <li><a href="#">Faq</a></li>
            <li><a href="#">Team</a></li>
            <li><a href="#">Testimonials</a></li>
            <li><a href="#">Contact</a></li>
            <li>
              <div class="navbar-btn-group">
                <a class="navbar-btn btn btn-success btn-block" href="{% url 'Accountant:sign_in' %}">Sign In</a>
              </div>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <div class="masthead" style="background-image:url('{% static 'img/back2.jpg' %}');">
      <div class="masthead-inner">
        <div class="container">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1" style="background-color: rgba(0,0,0,0.33)">
              <div class="row">
                <div class="col-sm-10 col-sm-offset-1" >
                  <h3 class="masthead-heading">The fastest way to build Modern Admin APPS for any platform, browser, or device.</h3>
                  <p class="masthead-lead">Elephant is a front-end template created to help you develop modern web applications, fast and in a professional manner. Built on top of Bootstrap, it includes a large collection of HTML, CSS, and JS components that is simple to use and easy to customise.</p>
                </div>
                <div class="col-sm-12 col-sm-offset-0">
                  <img class="masthead-img" src="img/4299815763.png" alt="Elephant">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="section">
      <div class="container">

      </div>
    </div>
    <div class="section">
      <div class="container">

      </div>
    </div>
    <div class="staff">
      <div class="container">

      </div>
    </div>

    <div class="testimonials">
      <div class="container">

          </div>
        </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-4">
            <h4 class="footer-heading">Elephant</h4>
            <p>
              <small>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis ac fermentum nibh, sit amet volutpat.</small>
            </p>
            <div class="social-list">
              <a class="social-list-item" href="#">
                <span class="icon icon-twitter"></span>
              </a>
              <a class="social-list-item" href="#">
                <span class="icon icon-facebook"></span>
              </a>
              <a class="social-list-item" href="#">
                <span class="icon icon-linkedin"></span>
              </a>
              <a class="social-list-item" href="#">
                <span class="icon icon-vimeo"></span>
              </a>
            </div>
          </div>
          <div class="col-sm-4 col-md-2 col-md-offset-2">
            <h4 class="footer-heading">Elephant</h4>
            <ul class="footer-links">
              <li>
                <a href="#">
                  <span class="icon icon-angle-right"></span>
                  About Us
                </a>
              </li>
            </ul>
          </div>
          <div class="col-sm-4 col-md-2">
            <h4 class="footer-heading">Help</h4>
            <ul class="footer-links">
              <li>
                <a href="#">
                  <span class="icon icon-angle-right"></span>
                  Help Center
                </a>
              </li>

            </ul>
          </div>
          <div class="col-sm-4 col-md-2">
            <h4 class="footer-heading">Upgrade</h4>
            <ul class="footer-links">
              <li>
                <a href="#">
                  <span class="icon icon-angle-right"></span>
                  Personal
                </a>
              </li>
            </ul>
          </div>
        </div>
        <p>© 2016 Elephant, LLC. All rights reserved.</p>
      </div>
    </div>
    <script src="{% static 'js/vendor.min.js'%}"></script>
    <script src="{% static 'js/elephant.min.js' %}s"></script>
    <script src="{% static 'js/landing-page.min.js' %}"></script>
  </body>
</html>

accountant/templates/accountant/sales.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
<div class="card">
    <div class="card-header">
        <strong>Stocks</strong>
        <a class="btn btn-success pull-right" href="{% url 'Accountant:add_sale' customer.id%}">Add Sale</a>
    </div>
    <div class="card-body">
        <div class="table-flip-scroll table-responsive">
            <table class="table table-striped dataTable">
                <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Units</th>
                </tr>
                </thead>
                <tbody>
                {% for sale in customer_sales %}
                <tr>
                    <td><a href="">{{ sale.product.name }}</a></td>
                    <td>{{ sale.price_per_unit }}</td>
                    <td>{{ sale.units_sold }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
</div>
{% endblock %}

accountant/templates/accountant/view_products.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
<div class="card">
    <div class="card-header">
        <strong>Products</strong>
        <a href="{% url 'Accountant:new_product' stock.id %}" class="btn btn-success pull-right">Add New Stock</a>
    </div>
    <div class="card-body">
        <div class="table-flip-scroll table-responsive">
            <table class="table table-striped dataTable">
                <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Units Purchased</th>
                    <th>Date Purchased</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.number_of_units }}</td>
                    <td>{{ product.created_at }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
</div>
{% endblock %}

accountant/templates/accountant/view_stocks.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="col-xs-12">
<div class="card">
    <div class="card-header">
        <strong>Stocks</strong>
        <a class="btn btn-success pull-right" href="{% url 'Accountant:new_stock' %}">Add New Stock</a>
    </div>
    <div class="card-body">
        <div class="table-flip-scroll table-responsive">
            <table class="table table-striped dataTable">
                <thead>
                <tr>
                    <th>Stock Name</th>
                    <th>Date Purchased</th>
                </tr>
                </thead>
                <tbody>
                {% for stock in stocks %}
                <tr>
                    <td><a href="{% url 'Accountant:products' stock.id %}">{{ stock.name }}</a></td>
                    <td>{{ stock.created_at }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
</div>
{% endblock %}